import bpy
from pathlib import Path
import math
import argparse, sys

parser = argparse.ArgumentParser()
parser.add_argument("--in")
parser.add_argument("--out")
params = vars(parser.parse_args(sys.argv[sys.argv.index("--") + 1 :]))


def centerObjectOriginToGeometry(obj):
    # To undo this later, the cursor must be aligned with the location of the object.
    bpy.context.scene.cursor.location = obj.location
    # Align the object's origin with the object's center.
    bpy.ops.object.origin_set(type="ORIGIN_GEOMETRY")


def render(x: Path):
    bpy.ops.import_scene.obj(
        filepath=str(x),
        axis_forward="-Z",
        axis_up="Y",
        filter_glob="*.obj;*.mtl",
        global_clamp_size=5,
    )

    modelName = x.stem
    obj = bpy.data.objects[modelName]
    assert obj

    centerObjectOriginToGeometry(obj)
    obj.location = (0, 0, 0)
    # TODO: This is empirical, may only work for me. Depends on orientation when exporting...
    obj.rotation_euler.z = -math.pi

    # Zoom out a bit, so we aren't touching the edges of the view.
    # We need blank film to apply an outline to the model.
    obj.select_set(True)
    bpy.ops.view3d.camera_to_view_selected()
    camera = bpy.context.scene.camera
    camera.data.ortho_scale *= 1.04

    bpy.context.scene.render.filepath = params["out"]
    bpy.ops.render.render(animation=False, write_still=True)

    #! Uncomment to save an autogenerated .blend file for debugging purposes.
    # bpy.ops.wm.save_as_mainfile(filepath="./out.blend")
    bpy.ops.object.delete()


render(Path(params["in"]))
